from enum import Enum


class EnDealAction(Enum):
    DEAL_BUY = 0
    DEAL_SELL = 1
    DEAL_BALANCE = 2
    DEAL_CREDIT = 3
    DEAL_CHARGE = 4
    DEAL_CORRECTION = 5
    DEAL_BONUS = 6
    DEAL_COMMISSION = 7
    DEAL_COMMISSION_DAILY = 8
    DEAL_COMMISSION_MONTHLY = 9
    DEAL_AGENT_DAILY = 10
    DEAL_AGENT_MONTHLY = 11
    DEAL_INTERESTRATE = 12
    DEAL_BUY_CANCELED = 13
    DEAL_SELL_CANCELED = 14
    DEAL_DIVIDEND = 15
    DEAL_DIVIDEND_FRANKED = 16
    DEAL_TAX = 17
    DEAL_AGENT = 18
    DEAL_SO_COMPENSATION = 19
    DEAL_SO_COMPENSATION_CREDIT = 20
    DEAL_FIRST = 0
    DEAL_LAST = 20


class EnDealEntry(Enum):
    ENTRY_IN = 0
    ENTRY_OUT = 1
    ENTRY_INOUT = 2
    ENTRY_OUT_BY = 3
    ENTRY_FIRST = 0
    ENTRY_LAST = 3
