default: &default
  runner: DockerRunner
  tests:
    - name: account-metrics-test
      template: .eaera-ci/docker-compose-test.yml.erb
      service_name: account-metrics
      result_attachments:
        - name: report
          type: zip
          files:
            - report.html
push:
  branches:
    main:
      <<: *default
pull_request:
  branches:
    main:
      <<: *default